name: Build and push EPGStation

on:
  push:
    branches:
      - main
    paths:
      - src/epgstation/*
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image: ghcr.io/hiroxto/epgstation
      context: ./src/epgstation
      platforms: linux/amd64
