name: Build check Docker images

on:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      epgstation: ${{ steps.filter.outputs.epgstation }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            epgstation:
              - src/epgstation/**

  epgstation:
    needs:
      - changes
    if: needs.changes.outputs.epgstation == 'true'
    uses: ./.github/workflows/build-check.yml
    with:
      context: ./src/epgstation
