name: Build Docker image

on:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      epgstation: ${{ steps.filter.outputs.epgstation }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            epgstation:
              - src/epgstation/**

  epgstation:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: needs.changes.outputs.epgstation == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build EPGStation
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/epgstation/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
