name: Build check Docker images

on:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-slim
    outputs:
      epgstation: ${{ steps.filter.outputs.epgstation }}
      mirakurun: ${{ steps.filter.outputs.mirakurun }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            epgstation:
              - src/epgstation/**
            mirakurun:
              - src/mirakurun/**

  epgstation:
    needs:
      - changes
    if: needs.changes.outputs.epgstation == 'true'
    uses: ./.github/workflows/build-check.yml
    with:
      context: ./src/epgstation

  mirakurun:
    needs:
      - changes
    if: needs.changes.outputs.mirakurun == 'true'
    uses: ./.github/workflows/build-check.yml
    with:
      context: ./src/mirakurun
