name: Build check Docker images

on:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-slim
    outputs:
      epgstation: ${{ steps.filter.outputs.epgstation }}
      mirakurun: ${{ steps.filter.outputs.mirakurun }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            epgstation:
              - src/epgstation/**
            mirakurun:
              - src/mirakurun/**

  epgstation:
    needs:
      - changes
    if: needs.changes.outputs.epgstation == 'true'
    uses: ./.github/workflows/build-check.yml
    with:
      context: ./src/epgstation

  mirakurun:
    needs:
      - changes
    if: needs.changes.outputs.mirakurun == 'true'
    uses: ./.github/workflows/build-check.yml
    with:
      context: ./src/mirakurun
